name: Do a test Build
on:
  pull_request:	
    branches: *	

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install mdbook
      run: curl -L "https://github.com/rust-lang/mdBook/releases/download/v0.4.6/mdbook-v0.4.6-x86_64-unknown-linux-gnu.tar.gz" | tar xvz
    - name: Test Build
      run: ./mdbook build

